In [3]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
type(l)

list

In [5]:
a = np.array(l)
type(a)

numpy.ndarray

In [12]:
a

array([1, 2, 3, 4, 5])

In [6]:
a1 = np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a2 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [11]:
a.ndim, a1.ndim, a2.ndim

(1, 2, 3)

In [16]:
a3 = np.asarray(l)
a3

array([1, 2, 3, 4, 5])

minimum 2D in matrix

In [17]:
a4 = np.matrix(l)
a4

matrix([[1, 2, 3, 4, 5]])

In [18]:
np.asanyarray(a3)

array([1, 2, 3, 4, 5])

In [19]:
np.asanyarray(a4)

matrix([[1, 2, 3, 4, 5]])

deepcopy and shallow copy

In [32]:
#shallow copy
a = [1,2,3,4]
a1 = a
a[0] = 5
a,a1

([5, 2, 3, 4], [5, 2, 3, 4])

In [33]:
#deepcopy
a2 = np.copy(a)
a2

array([5, 2, 3, 4])

In [34]:
a[2] = 41
a2,a

(array([5, 2, 3, 4]), [5, 2, 41, 4])

In [38]:
np.fromfunction(lambda i,j : i == j, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [44]:
np.random.rand(2,3,2,2)

array([[[[0.78571497, 0.50143832],
         [0.79089506, 0.38807456]],

        [[0.7087363 , 0.25980584],
         [0.23994437, 0.6465153 ]],

        [[0.53875196, 0.93467806],
         [0.85596585, 0.05436983]]],


       [[[0.78733429, 0.63338991],
         [0.51032574, 0.95920928]],

        [[0.60527426, 0.51801821],
         [0.23198049, 0.45982065]],

        [[0.17988487, 0.35496824],
         [0.4095384 , 0.40803591]]]])

This code uses the `numpy` library's random number generator to create an n-dimensional array of shape `(2,3,2,2)`, i.e., a 4-dimensional array with 2 elements along the first axis, 3 elements along the second axis, 2 elements along the third axis, and 2 elements along the fourth axis.

In [45]:
np.random.randn(2,3,2,2)

array([[[[ 1.12625945, -0.2777836 ],
         [-1.23038339,  0.71216864]],

        [[ 1.24427565,  0.52701066],
         [-0.67875694,  0.12389497]],

        [[ 0.57435668,  0.62187876],
         [-0.42888381, -0.3745623 ]]],


       [[[-1.21584252, -0.42531378],
         [-1.17782152, -0.36114027]],

        [[-1.76938135, -0.61156804],
         [-0.97624988,  1.39347922]],

        [[-0.8959982 , -1.72496344],
         [ 0.24797763,  0.12922098]]]])

In [47]:
d1= np.random.randint(0,10,(4,4,2))
d1

array([[[3, 4],
        [8, 1],
        [7, 5],
        [4, 2]],

       [[0, 5],
        [1, 5],
        [0, 6],
        [2, 7]],

       [[5, 2],
        [7, 8],
        [2, 7],
        [4, 6]],

       [[5, 7],
        [6, 3],
        [8, 5],
        [4, 3]]])

This code uses the `numpy` library's random number generator to create an n-dimensional array of shape `(4, 4, 2)`, i.e., a 3-dimensional array with 4 elements along the first axis, 4 elements along the second axis, and 2 elements along the third axis. The `randint` function generates random integers from a uniform distribution between the lower bound `0` and upper bound `10`, so each element in the array will be a random integer between 0 (inclusive) and 10 (exclusive).

In [50]:
d1.reshape(16,2)

array([[3, 4],
       [8, 1],
       [7, 5],
       [4, 2],
       [0, 5],
       [1, 5],
       [0, 6],
       [2, 7],
       [5, 2],
       [7, 8],
       [2, 7],
       [4, 6],
       [5, 7],
       [6, 3],
       [8, 5],
       [4, 3]])

In [1]:
range(0,10)

range(0, 10)

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
list(range(0.5,14,3))

TypeError: 'float' object cannot be interpreted as an integer

can generate floating point numbers

In [6]:
np.arange(0.5,14,3)

array([ 0.5,  3.5,  6.5,  9.5, 12.5])

The start value is `5`, the end value is `-4`, and the step size is `-1`, so the function generates a sequence of numbers counting down from `5` to `-4`.

In [12]:
np.arange(5,-4,-1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [15]:
np.arange(5,-4)

array([], dtype=int32)

`np.arange(5, -4)` does not produce any output because, by default, the step size is set to `1`, and counting up from `5` to `-4` would not result in any numbers being generated.

In [4]:
np.linspace(1,5,20)


array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [18]:
np.linspace(1,5,20, retstep= True)

(array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367)

In [19]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [27]:
np.ones((5,2,7))+5

array([[[6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.]]])

In [28]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
a = np.eye(5) +3
a

array([[4., 3., 3., 3., 3.],
       [3., 4., 3., 3., 3.],
       [3., 3., 4., 3., 3.],
       [3., 3., 3., 4., 3.],
       [3., 3., 3., 3., 4.]])

In [36]:
a.size, a.ndim, a.shape

(25, 2, (5, 5))

In [7]:
a1 = np.random.randn(3,4)
a1

array([[-0.54859922,  2.72045282,  1.45491168,  1.52566926],
       [-0.00419252,  0.69805294,  1.4104494 ,  1.04234565],
       [-0.67944535, -0.2491132 , -0.70855885, -0.89683129]])

In [9]:
a1[1][2]

1.4104494038593145

In [23]:
a1[0:2,0:2]

array([[-0.54859922,  2.72045282],
       [-0.00419252,  0.69805294]])

In [15]:
import pandas as pd 
a2 = pd.DataFrame(a1)
a2

0         1         2         3
0 -0.548599  2.720453  1.454912  1.525669
1 -0.004193  0.698053  1.410449  1.042346
2 -0.679445 -0.249113 -0.708559 -0.896831

In [22]:
a2.loc[0:1,[0,1]]

0         1
0 -0.548599  2.720453
1 -0.004193  0.698053

In [24]:
m1 = np.random.randint(1,3,(3,3))
m2 = np.random.randint(2,4,(3,3))
m1,m2

(array([[1, 1, 2],
        [2, 1, 1],
        [1, 2, 2]]),
 array([[2, 3, 3],
        [3, 3, 3],
        [2, 2, 2]]))

In [25]:
#element wise multiplication
m1*m2

array([[2, 3, 6],
       [6, 3, 3],
       [2, 4, 4]])

In [26]:
#matrix mul
m1@m2

array([[ 9, 10, 10],
       [ 9, 11, 11],
       [12, 13, 13]])

In [27]:
pow(m1, 4)

array([[ 1,  1, 16],
       [16,  1,  1],
       [ 1, 16, 16]], dtype=int32)